### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by f0reclone** [asahasrabuddhe/laravel-mjml#9]
Hello, I'm using the current version of your library and it works great if installed with yarn and the path is configured. I've noticed there are some caching issues:
I'm calling the mjml on a blade view lets say password-reset.blade.php, that extends a master mjml-master.blade.php file. If I change the content of the password reset the whole view gets updated. If I change the master file the view doesn't get updated. Also if any include view of the master gets updated there is no change.
Simplified version of the files
// mjml-master.blade.php
```
<mjml>
    <mj-head>
        @include('emails.partials.db-head')
    </mj-head>
    <mj-body background-color="#fff">
        @yield('content')
    </mj-body>
</mjml>
```

// password-reset.blade.php
```
@extends('emails.mjml-master')
@section('content')
    <mj-section padding="20px 20px 20px 20px" background-color="#FFFFFF">
        <mj-column>
            <mj-text align="center" font-weight="300" padding="30px 40px 10px 40px" font-size="28px" line-height="40x"
                     color="#5190c1">Did you forget your Password?
            </mj-text>
        </mj-column>
    </mj-section>
@stop
```

**Comment by f0reclone** [comment]
Did some digging in your Code:
```
public function isExpired()
    {
        if (! File::exists($this->compiledPath)) {
            return true;
        }
        return File::lastModified($this->view->getPath()) >=
            File::lastModified($this->compiledPath);
    }
```
This function only works correctly if there is only one view file per email and no parameters passed to the view. My recommendation would be to disable caching.

**Comment by asahasrabuddhe** [comment]
Let me take a look

**Comment by fsasvari** [comment]
Yeah, same problem here. It does not clear compiled MJML views from "storage/framework/views" directory and it always sends the same password reset link to all users.

**Comment by fsasvari** [comment]
@asahasrabuddhe is this fixed ?
